homeassistant: true
zigbee_herdsman_debug: true
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: true
mqtt:
  server: mqtt://192.168.33.3:1883
  basetopic: zigbee2mqtt
  user: homeassistant
  password: ahThoh1ahg9sheidohb2jahXem5Araimaiveebeivief6kugeey7taiqu5ahh6lu
frontend:
  port: 8099
ota:
  ikea_ota_use_test_url: false
  update_check_interval: 1440
  disable_automatic_update_check: false
serial:
  port: tcp://192.168.33.12:8888
  baudrate: 115200
  disable_led: false